feat: SRE-1122 - Migration from CircleCI to GH Actions

diff --git a/.github/workflows/behat-tests.yml b/.github/workflows/behat-tests.yml
--- a/.github/workflows/behat-tests.yml
+++ b/.github/workflows/behat-tests.yml
@@ -96,17 +96,105 @@ jobs:
 
       - name: Validate Fixture Version
         run: |
-          wget -q https://gist.githubusercontent.com/jazzsequence/13f2493d09a/raw/19056fe59fd2dc2e2fb62051e96fb2d5bb63bfe3/validate-fixture-version.sh -O ./bin/validate-fixture-version.sh
-          
-          # Fix 1: Change PHP exit code behavior
-          sed -i "s/exit(version_compare/echo version_compare/g" ./bin/validate-fixture-version.sh
+          # Create a corrected version of the script directly
+          cat << 'EOF' > ./bin/validate-fixture-version.sh
+          #!/bin/bash
+          set -euo pipefail
+          IFS=$'\n\t'
 
-          # Fix 2: Add flags/args to upstream:updates:apply and add --verbose for debugging
-          sed -i 's/terminus upstream:updates:apply/terminus upstream:updates:apply --verbose --accept-upstream "${TERMINUS_SITE}".dev/g' ./bin/validate-fixture-version.sh
+          main(){
+              export TERMINUS_HIDE_GIT_MODE_WARNING=1
+              local DIRNAME
+              DIRNAME=$(dirname "$0")
 
-          # Fix 3: Add connection:set to ensure Git mode and add --verbose for debugging
-          sed -i '/echo "Applying upstream updates on/a \\ \ \ \ \ terminus connection:set --verbose "${TERMINUS_SITE}".dev git' ./bin/validate-fixture-version.sh
+              local CURRENT_WP_VERSION
+              CURRENT_WP_VERSION=$(curl -s https://api.wordpress.org/core/version-check/1.7/ | jq -r '.offers[0].current')
+              echo "Current WordPress Version: ${CURRENT_WP_VERSION}"
 
+              if [ -z "${TERMINUS_SITE}" ]; then
+                  echo "TERMINUS_SITE environment variable must be set"
+                  exit 1
+              fi
+
+              if ! terminus whoami > /dev/null; then
+                  if [ -z "${TERMINUS_TOKEN}" ]; then
+                      echo "TERMINUS_TOKEN environment variable must be set or terminus already logged in."
+                      exit 1
+                  fi
+                  terminus auth:login --machine-token="${TERMINUS_TOKEN}"
+              fi
+
+              # Use find to locate the file with a case-insensitive search
+              README_FILE_PATH=$(find "${DIRNAME}"/.. -iname "readme.txt" -print -quit)
+              if [[ -z "$README_FILE_PATH" ]]; then
+                  echo "readme.txt not found."
+                  exit 1
+              fi
+
+              local TESTED_UP_TO
+              TESTED_UP_TO=$(grep -i "Tested up to:" "${README_FILE_PATH}" | tr -d '\r\n' | awk -F ': ' '{ print $2 }')
+              echo "Tested Up To: ${TESTED_UP_TO}"
+              local FIXTURE_VERSION
+              FIXTURE_VERSION=$(terminus wp "${TERMINUS_SITE}.dev" -- core version)
+              echo "Fixture Version: ${FIXTURE_VERSION}"
+
+              local FIXTURE_VERSION_COMPARE
+              FIXTURE_VERSION_COMPARE=$(php -r "echo version_compare('${FIXTURE_VERSION}', '${CURRENT_WP_VERSION}');")
+              if [[ $FIXTURE_VERSION_COMPARE -eq -1 ]]; then
+                  echo "Fixture Version: ${FIXTURE_VERSION} is less than Current WordPress Version: ${CURRENT_WP_VERSION}"
+                  echo "Setting connection to git mode..."
+                  terminus connection:set "${TERMINUS_SITE}".dev git
+                  echo "Applying upstream updates on ${TERMINUS_SITE}.dev"
+                  terminus upstream:updates:apply --accept-upstream "${TERMINUS_SITE}".dev
+              fi
+
+              local VERSION_COMPARE
+              VERSION_COMPARE=$(php -r "echo version_compare('${TESTED_UP_TO}', '${FIXTURE_VERSION}');")
+
+              local WP_VERSION_COMPARE
+              WP_VERSION_COMPARE=$(php -r "echo version_compare('${TESTED_UP_TO}', '${CURRENT_WP_VERSION}');")
+
+              if [[ $WP_VERSION_COMPARE -eq 0 ]]; then
+                  echo "Tested Up To: ${TESTED_UP_TO} matches Current WordPress Version: ${CURRENT_WP_VERSION}"
+              elif [[ $WP_VERSION_COMPARE -eq 1 ]]; then
+                  echo "Tested Up To: ${TESTED_UP_TO} is greater than Current WordPress Version: ${CURRENT_WP_VERSION}"
+              else
+                  echo "Tested Up To: ${TESTED_UP_TO} does not match Current WordPress Version: ${CURRENT_WP_VERSION}"
+                  echo "Please update ${TESTED_UP_TO} to ${CURRENT_WP_VERSION}"
+                  exit 1
+              fi
+
+              if [[ $VERSION_COMPARE -eq 0 ]]; then
+                  echo "Tested Up To: ${TESTED_UP_TO} matches Fixture Version: ${FIXTURE_VERSION}"
+                  exit 0
+              fi
+
+              if [[ $VERSION_COMPARE -eq -1 ]]; then
+                  echo "${TESTED_UP_TO} is less than ${FIXTURE_VERSION}"
+                  echo "Please update ${TESTED_UP_TO} to ${FIXTURE_VERSION}"
+                  exit 1
+              fi
+
+              if [[ $VERSION_COMPARE -eq 1 ]]; then
+                  echo "${FIXTURE_VERSION} is less than ${TESTED_UP_TO}"
+
+                  read -r CURRENT_MAJOR CURRENT_MINOR <<<$(echo "$CURRENT_WP_VERSION" | awk -F. '{print $1, $2}')
+                  NEXT_MAJOR_VERSION="${CURRENT_MAJOR}.$((${CURRENT_MINOR}+1))"
+
+                  if [[ "$TESTED_UP_TO" == "$NEXT_MAJOR_VERSION" ]]; then
+                      echo "Tested Up To: ${TESTED_UP_TO} is the next major version after the Current WordPress Version: ${CURRENT_WP_VERSION}"
+                      echo "Ensure you have validated that the plugin works on the next major version of WordPress or update ${TERMINUS_SITE} to a pre-release version."
+                  else
+                      echo "Tested Up To: ${TESTED_UP_TO} is not the next major version (${NEXT_MAJOR_VERSION}). This seems like an error. Please review."
+                      exit 1
+                  fi
+              fi
+          }
+
+          main
+          EOF
+
+          # Make the new script executable and run it
           chmod +x ./bin/validate-fixture-version.sh
           ./bin/validate-fixture-version.sh
 
